name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  NODE: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"

      - name: Install Dependencies
        working-directory: frontend/shishiodoshi
        run: yarn install

      - name: Build Application
        working-directory: frontend/shishiodoshi
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOYKEY }}
          publish_dir: ./frontend/shishiodoshi/dist